"""Streamlit entry point. Run with `gbflex gui`, not by importing this module."""

from __future__ import annotations

import os
from pathlib import Path

import pandas as pd
import streamlit as st
import yaml

from gb_flexabm import __version__
from gb_flexabm.data import CATALOG, calendar_coverage, validate_data_manifest
from gb_flexabm.era5 import AREA, GROUPS
from gb_flexabm.workbench import create_run, read_result, run_bundle, saved_runs, scenario, seed_set


def results(output: Path) -> None:
    # Verify on every rerender; a modified file must not retain a green status or export button.
    record, config = read_result(output)
    summary = pd.read_csv(output / "summary.csv")
    annual = pd.read_csv(output / "annual.csv")
    st.subheader("Verified experiment results")
    st.success("Output checksums and stored model checks pass — not empirical validation.")
    st.caption(
        f"Saved assumptions: {config['hours']} synthetic periods/year · "
        f"{config['years'][0]}–{config['years'][-1]} · "
        f"seeds {', '.join(map(str, record['random_seeds']))} · "
        f"base demand {config['base_demand_mw'] / 1000:g} GW · "
        f"growth {100 * config['demand_growth_fraction']:g}% · "
        f"payment £{config['capacity_price_gbp_per_kw_year']:g}/kW/year. "
        "Editing the form does not change this saved run."
    )
    means = summary.groupby("design").resource_npv_gbp.mean()
    a, b, c = st.columns(3)
    a.metric("Planner resource NPV", f"£{summary.planner_npv_gbp.iloc[0] / 1e9:,.3f} bn")
    b.metric("Energy-only mean NPV", f"£{means['energy_only'] / 1e9:,.3f} bn")
    c.metric(
        "Payment − energy-only mean NPV",
        f"£{(means['stylised_capacity_payment'] - means['energy_only']) / 1e9:,.3f} bn",
    )
    st.caption(
        "Resource costs exclude capacity-payment transfers. Seed variation is synthetic, "
        "not calibrated uncertainty. A zero paired effect is possible and is not a policy conclusion."
    )
    st.image(
        str(output / "comparison.png"), caption="Generated by the same report engine as the CLI."
    )
    with st.expander("Inspect tables and provenance"):
        st.markdown("**Per-seed resource costs (GBP)**")
        st.dataframe(summary, hide_index=True)
        st.markdown("**Annual audit table (units in column names)**")
        st.dataframe(annual, hide_index=True)
        st.json(record)
        st.json(config)
    st.code(f'gbflex verify --run "{output}"', language="shell")
    left, right = st.columns(2)
    left.download_button(
        "Download verified run (.zip)",
        run_bundle(output),
        file_name=f"gbflex-{record['run_id'][:12]}.zip",
        mime="application/zip",
        on_click="ignore",
    )
    right.download_button(
        "Download saved scenario (.yaml)",
        yaml.safe_dump(config, sort_keys=False),
        file_name="gbflex-scenario.yaml",
        mime="application/yaml",
        on_click="ignore",
    )


def experiment(root: Path) -> None:
    st.subheader("Configure a paired experiment")
    st.write("Both market designs share the same assumptions, seeds and physical model.")
    with st.form("experiment"):
        a, b, c = st.columns(3)
        hours = a.selectbox("Synthetic periods per year", (24, 48, 168), key="hours")
        years = a.number_input("Model years (from 2026)", 2, 6, 6, key="years")
        demand = b.number_input("Base demand (GW)", 1.0, 60.0, 25.0, key="demand")
        growth = b.number_input("Annual demand growth (%)", -5.0, 10.0, 2.5, key="growth")
        payment = c.number_input("Capacity payment (£/kW/year)", 0.0, 300.0, 75.0, key="payment")
        first = c.number_input("First random seed", 0, 1_000_000_000, 11, key="first")
        count = a.number_input("Paired seed count", 1, 10, 2, key="count")
        st.caption(
            "24–168 periods are repeated synthetic blocks weighted to 8,760 hours, "
            "not validated representative periods. Larger ensembles and annual benchmarks use the CLI. "
            "A run can take several seconds to a minute; no data is downloaded."
        )
        submitted = st.form_submit_button("Run paired experiment", type="primary")
    if submitted:
        st.session_state.pop("active_run", None)
        try:
            config = scenario(hours, int(years), demand, growth, payment)
            with st.spinner("Solving the planner and paired investor experiments…"):
                output = create_run(root, config, seed_set(int(first), int(count)))
            st.session_state["active_run"] = str(output)
        except (ValueError, RuntimeError, OSError, AssertionError, KeyError, TypeError) as exc:
            st.error(f"Experiment failed: {exc}. No successful result is shown for this attempt.")
    with st.expander("Reopen a local run"):
        choices = saved_runs(root)
        if choices:
            chosen = st.selectbox(
                "Saved run folder (newest first)", choices, format_func=lambda p: p.name
            )
            if st.button("Open saved run"):
                st.session_state["active_run"] = str(chosen)
        else:
            st.caption(
                "No completed GUI runs yet. New experiments are saved in separate local folders."
            )
    if active := st.session_state.get("active_run"):
        try:
            output = Path(active)
            if output not in saved_runs(root):
                raise ValueError("Selected run is not in the local GUI run directory")
            results(output)
        except (ValueError, RuntimeError, OSError, AssertionError, KeyError, TypeError) as exc:
            st.session_state.pop("active_run", None)
            st.error(f"Saved result could not be verified: {exc}. Exports are disabled.")
    else:
        st.info("Run an experiment to see the comparison, audit tables and downloadable evidence.")


def data_readiness() -> None:
    st.subheader("Historical data readiness")
    st.warning(
        "Observed data is not connected to these synthetic experiments. Calibration has not started."
    )
    st.dataframe(
        pd.DataFrame([{"source": key, **value} for key, value in CATALOG.items()])[
            ["source", "publisher", "status"]
        ],
        hide_index=True,
    )
    with st.expander("ERA5 selection and safe monthly downloads"):
        st.write(
            "Reanalysis only · hourly · 0.25° grid · training years 2013–2018. "
            "72 monthly requests plus one static download; not the entire ERA5 catalogue."
        )
        st.caption(
            f"Working bounding box [north, west, south, east]: {AREA}. Fleet masking is still required."
        )
        st.dataframe(
            pd.DataFrame(
                [
                    {"group": group, "variable": variable}
                    for group, variables in GROUPS.items()
                    for variable in variables
                ]
            ),
            hide_index=True,
            height=540,
        )
        st.code(
            "uv sync --locked --extra gui --extra research --extra dev\n"
            "uv run --locked --extra research python scripts/fetch_era5.py fetch --ids static,2013-01 --limit 2\n"
            "uv run --locked --extra research python scripts/fetch_era5.py fetch --limit 73",
            language="shell",
        )
        st.warning(
            "Run acquisition explicitly in a terminal; enter the token at the hidden prompt. "
            "The GUI never stores or submits credentials. A queued job resumes from its saved ID. "
            "Raw weather downloads do not complete S2 or establish calibrated availability."
        )
        st.link_button(
            "Full data checklist and download guide",
            "https://github.com/abhijith-sivaprasadan/gb-flexabm/blob/main/docs/HISTORICAL_DATA.md",
        )
    st.write(
        "The calendar gate requires every half-hour of the declared year, including leap days "
        "and GB daylight-saving transitions. Checksums alone cannot establish completeness."
    )
    manifests = sorted(Path("data/raw/neso-demand").glob("*/*/manifest.json"))
    with st.form("coverage"):
        initial_year = int(manifests[0].parent.parent.name) if manifests else 2024
        year = st.number_input("Expected calendar year", 1900, 2100, initial_year, key="data_year")
        selected = (
            st.selectbox("Local NESO manifest", manifests, format_func=str) if manifests else None
        )
        check = st.form_submit_button("Check calendar coverage", disabled=not manifests)
    if check and selected:
        try:
            frame = validate_data_manifest(selected, expected_year=int(year))
            st.success("Manifest integrity and complete calendar coverage pass.")
            st.json(calendar_coverage(frame, int(year)))
        except (ValueError, OSError, KeyError, TypeError) as exc:
            st.error(f"Data gate failed: {exc}")
    if not manifests:
        st.caption(
            "No local demand manifests found. Fetch explicitly with the CLI from the repository directory."
        )
    st.code(
        "gbflex data fetch --source neso-demand --year 2024\n"
        "gbflex data validate --manifest PATH_PRINTED_BY_FETCH --year 2024",
        language="shell",
    )
    st.caption(
        "The 2024 demand file was previously inspected for ingestion verification. "
        "There is no pristine holdout or predictive-skill claim. Source data retains NESO's licence."
    )


def main() -> None:
    st.set_page_config(
        page_title="GB-FLEXABM · Experiment workbench", page_icon="⚡", layout="wide"
    )
    # Streamlit dims captions; keep their effective contrast readable on the light theme.
    st.markdown(
        "<style>[data-testid='stCaptionContainer'], [data-testid='stImageCaption'] "
        "{opacity: 1 !important;} "
        "[data-testid='stCaptionContainer'], [data-testid='stCaptionContainer'] * "
        ", [data-testid='stImageCaption'] {color: #475569 !important;} "
        "[data-testid='stJson'] *, [data-testid='stAlert'] p, pre code, pre code * "
        "{color: #18232d !important;}</style>",
        unsafe_allow_html=True,
    )
    # Streamlit dims captions; keep their effective contrast readable on the light theme.
    st.markdown(
        "<style>[data-testid='stCaptionContainer'] {opacity: 1 !important;} "
        "[data-testid='stCaptionContainer'], [data-testid='stCaptionContainer'] * "
        "{color: #475569 !important;}</style>",
        unsafe_allow_html=True,
    )
    st.title("GB-FLEXABM")
    st.markdown("### Electricity investment · Experiment workbench")
    st.caption(f"Software v{__version__} · Independent research software · Local execution")
    st.warning(
        "Exploratory, synthetic and uncalibrated. This is not a GB forecast, an official "
        "market model, or evidence for policy or investment decisions."
    )
    run_tab, data_tab, plan_tab = st.tabs(["Experiment", "Data readiness", "Delivery plan"])
    with run_tab:
        experiment(Path(os.environ.get("GBFLEX_GUI_RUNS", "runs/gui")).resolve())
    with data_tab:
        data_readiness()
    with plan_tab:
        st.subheader("A staged research programme")
        st.markdown(
            "- **S0 — Done:** shared dispatch/planner, investors, audit trails and reference experiments.\n"
            "- **S1 — Implemented:** local workbench, calendar coverage gate and delivery contract.\n"
            "- **S2 — In progress:** training-demand audit, split guards and resumable ERA5 acquisition; full bundle pending.\n"
            "- **S3 — Utilities tested:** exogenous medoids and storage-reset error diagnostics; empirical baseline pending.\n"
            "- **S4 — Utilities tested:** trial registry, sensitivity screen and transfer arithmetic; historical institutions/fitting pending.\n"
            "- **S5 — Utilities tested:** lock checks, seed and baseline metrics; locked evaluation and independent review pending.\n"
            "- **S6 — Pending:** separately verified network, flexibility, heat and hydrogen extensions."
        )
        st.write(
            "Every milestone must update the README and portfolio, pass checks, and be pushed with publication verified."
        )
        st.link_button(
            "Read delivery gates and acceptance criteria",
            "https://github.com/abhijith-sivaprasadan/gb-flexabm/blob/main/docs/ROADMAP.md",
        )


if __name__ == "__main__":
    main()
